# Generated by Django 5.0.2 on 2024-02-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
